language: python
python: 
  - "2.6"
  - "2.7"
  - "3.3"
services:
  - mongodb
virtualenv:
  system_site_packages: true

install: "pip install -r requirements.txt"
script:
 - nosetests webapp/start.py lib/Storage.py lib/StoredObject.py modules/acquisition/PubMed.py

matrix:
  allow_failures:
    - python: "3.3"