language: python
python: 
  - "2.6"
  - "2.7"
  - "3.3"
  - "pypy"
services:
  - mongodb
virtualenv:
  system_site_packages: true

install: "pip install -r requirements.txt"
script:
 - nosetests webapp/start.py lib/*.py modules/acquisition/*.py core/*.py

matrix:
  allow_failures:
    - python: "3.3"
    - python: "pypy"
