language: python
python: 
  - "2.6"
  - "2.7"
virtualenv:
  system_site_packages: true

install: "pip install -r requirements.txt"
script:
 - nosetests webapp/start.py
 - cd lib/ nosetests Storage.py
