language: python
python: 
  - "2.6"
  - "2.7"
before_install:
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv
  - echo 'deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart 10gen' | sudo tee /etc/apt/sources.list.d/mongodb.list
  - sudo apt-get update
  - sudo apt-get install mongodb-10gen
virtualenv:
  system_site_packages: true

install: "pip install -r requirements.txt"
script:
 - nosetests webapp/start.py lib/Storage.py
