language: python
python: 
  - "2.6"
  - "2.7"
services:
  - mongodb
virtualenv:
  system_site_packages: true

install: "pip install -r requirements.txt"
script:
 - nosetests webapp/start.py lib/Storage.py lib/StoredObject.py
